jiaxincui@Jiaxins-MacBook-Pro-2 LLM-Automation % /usr/local/bin/python3.10 /Users/jiaxincui/VSCode/LLM-Automati
on/scripts/gpt4o/version1/execution4/step6
Traceback (most recent call last):
  File "/Users/jiaxincui/VSCode/LLM-Automation/scripts/gpt4o/version1/execution4/step6", line 53, in <module>
    main()
  File "/Users/jiaxincui/VSCode/LLM-Automation/scripts/gpt4o/version1/execution4/step6", line 30, in main
    merged_df = pd.merge(appointment_counts_df, reappointment_counts_df, how='outer', on=['org', 'year'], suffixes=('_appointments', '_reappointments'))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 110, in merge
    op = _MergeOperation(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 703, in __init__
    ) = self._get_merge_keys()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 1162, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/generic.py", line 1850, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'year'


jiaxincui@Jiaxins-MacBook-Pro-2 LLM-Automation % /usr/local/bin/python3.10 /Users/jiaxincui/VSCode/LLM-Automati
on/scripts/gpt4o/version1/execution4/step6

Employee Counts Columns:
Index(['org', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020',
       '2021', '2022', '2023', '2024'],
      dtype='object')

Reappointment Counts Columns:
Index(['org', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020',
       '2021', '2022', '2023', '2024'],
      dtype='object')
Traceback (most recent call last):
  File "/Users/jiaxincui/VSCode/LLM-Automation/scripts/gpt4o/version1/execution4/step6", line 60, in <module>
    main()
  File "/Users/jiaxincui/VSCode/LLM-Automation/scripts/gpt4o/version1/execution4/step6", line 37, in main
    merged_df = pd.merge(appointment_counts_df, reappointment_counts_df, how='outer', on=['org', 'year'], suffixes=('_appointments', '_reappointments'))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 110, in merge
    op = _MergeOperation(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 703, in __init__
    ) = self._get_merge_keys()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 1162, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/generic.py", line 1850, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'year'



jiaxincui@Jiaxins-MacBook-Pro-2 LLM-Automation % /usr/local/bin/python3.10 /Users/jiaxincui/VSCode/LLM-Automati
on/scripts/gpt4o/version1/execution4/step7
Traceback (most recent call last):
  File "/Users/jiaxincui/VSCode/LLM-Automation/scripts/gpt4o/version1/execution4/step7", line 73, in <module>
    main()
  File "/Users/jiaxincui/VSCode/LLM-Automation/scripts/gpt4o/version1/execution4/step7", line 44, in main
    top_orgs = top_orgs.groupby('year').first().reset_index()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/frame.py", line 8402, in groupby
    return DataFrameGroupBy(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 965, in __init__
    grouper, exclusions, obj = get_grouper(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/groupby/grouper.py", line 878, in get_grouper
    obj._check_label_or_level_ambiguity(gpr, axis=axis)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/generic.py", line 1797, in _check_label_or_level_ambiguity
    raise ValueError(msg)
ValueError: 'year' is both an index level and a column label, which is ambiguous.